version: "3"
services:
    db:
        #image: mysql:5.7
        #environment:
            #MYSQL_ROOT_PASSWORD: dbpassword_for_user
            #MYSQL_DATABASE: eval_server_development
            #MYSQL_USER: db_username
            #MYSQL_PASSWORD: dbpassword_for_user
        #restart: always
    eval:
        #build: evaluationserver
        #env_file: evaluationserver/env
        #command: "./bin/wait-for-it.sh db:3306 -s -t 30 -- ./bin/docker_start"
        #volumes:
        #- ./evaluationserver:/usr/src/app
        #ports:
            #- "8081:8081" 
        #depends_on:
            #- db
    frontend:
        restart: always
        image: php:7.1.11-apache
        volumes:
            - ./ui:/var/www/html
        ports:
            - "8082:8082"
    backend:
        build: generator2/org.getaviz.generator/
        restart: always
        volumes:
            - ./generator2/org.getaviz.generator/target/org.getaviz.generator-1.0.0-SNAPSHOT.war:/var/lib/jetty/webapps/root.war
            - ./settings.properties:/opt/config/settings.properties
            - ./generator2/output:/opt/output/
            - ./generator2/databases:/opt/databases/
        ports:
            - "8083:8080"
volumes:
  bundle:
    driver: local
