# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 232212764bc8a410c68067442938ad5a764ae7e7a2ea93d1933c6a0270d8c88f61ed2462563a9a0244827067ef32fc4c7f464280c713bfda20c2459b89d78425

test:
  secret_key_base: 87b8d6ee10fbff1daaffcdbf2c63c9348d455ce4ee58b33dbeefe45d8c1d706d9238ae7d60fec694a0cc5f038d3935057943e9644b47ca106cf1b4cb86f17d39

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= Rails.application.credentials.secret_key_base %>
